// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-05YlQDp64z_cy3i2-kNUJr7N9ovKoKs',
    appId: '1:772374019992:web:157b36d14f0beea9e235ed',
    messagingSenderId: '772374019992',
    projectId: 'devpad-xi',
    authDomain: 'devpad-xi.firebaseapp.com',
    storageBucket: 'devpad-xi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANegNeJJFx1a5qe7-ATQD-wXAOoHAGYSA',
    appId: '1:772374019992:android:7e1f32aa2cbc2088e235ed',
    messagingSenderId: '772374019992',
    projectId: 'devpad-xi',
    storageBucket: 'devpad-xi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-05YlQDp64z_cy3i2-kNUJr7N9ovKoKs',
    appId: '1:772374019992:web:157b36d14f0beea9e235ed',
    messagingSenderId: '772374019992',
    projectId: 'devpad-xi',
    authDomain: 'devpad-xi.firebaseapp.com',
    storageBucket: 'devpad-xi.firebasestorage.app',
  );
}
